//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQCustomers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPhamTheoNguoiDung
    {
        public long ID { get; set; }
        public string QRCode { get; set; }
        public string URLSanPham { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> NgayLuuSanPham { get; set; }
        public string HinhSanPham { get; set; }
    }
}
